Add support for windows developers
*  Locally setting git to NOT convert from unix to windows style line endings.
*  Including COMPOSE_CONVERT_WINDOWS_PATHS=1 in .env.example.

Signed-off-by: jbobo <j.ned@bobonana.me>

diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -35,6 +35,12 @@ EOM
 
 }
 
+if ! [ -e .env.example] 
+then
+    echo ".env file not found. Creating one from .env.example ..."
+    cp ./.env.example ./.env
+fi
+
 if [[ "$1" =~ ^((-{1,2})([Hh]$|[Hh][Ee][Ll][Pp])|)$ ]]; then
     usage; exit 1
 else
